core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views
from .views import autosuggest, json_bed_edit

urlpatterns = [
    # path("", views.index, name="index"),
    path("", views.dashboard, name="dashboard"),
    path("dashboard2/", views.dashboard2, name="dashboard2"),
    path("base/", views.base, name="base"),    
    path("login/", views.login, name="login"),
    path("forgot_password/", views.forgot_password, name="forgot_password"),
    path('logout', views.logout, name='logout'),
    path("add_patient/", views.add_patient, name="add_patient"),
    path("add_patient_admin/", views.add_patient_admin, name="add_patient_admin"),
    path("patient_list/", views.patient_list, name="patient_list"),
    path("patient_list_admin/", views.patient_list_admin, name="patient_list_admin"),
    path("patient_list/patient/<pk>/", views.patient, name="patient"),
    path("patient_list_admin/patient/<pk>/", views.patient_admin, name="patient_admin"),
    path("autosuggest/", views.autosuggest, name="autosuggest"),
    path("autodoctor/", views.autodoctor, name="autodoctor"),
    path("autobed/", views.autobed, name="autobed"),
    path("info/", views.info, name="info"),
    path("add_bed/", views.add_bed, name="add_bed"),
    path("add_bed_admin/", views.add_bed_admin, name="add_bed_admin"),
    path("view_bed/", views.view_bed, name="view_bed"),
    path("view_bed_admin/", views.view_bed_admin, name="view_bed_admin"),
    path("view_bed/update_bed/<pk>/", views.update_bed, name="update_bed"),
    path("view_bed_admin/update_bed/<pk>/", views.update_bed_admin, name="update_bed_admin"),
    path("add_user/", views.add_user, name="add_user"),
    path("user_list/", views.user_list, name="user_list"),
    path("user_list/user_update/<pk>/", views.user_update, name="user_update"),
    path('add_doctor/',views.add_doctor,name="add_doctor"),
    path('view_doctor/',views.view_doctor,name="view_doctor"),
    path('view_doctor/update_doctor/<pk>/',views.update_doctor,name="update_doctor"),
    path('view_ur_patient/doctor_edit_patient/<pk>/',views.doctor_edit_patient,name="doctor_edit_patient"),
    path('bed_master_data/',views.bed_master.as_view()), 
    path('patient_master_data/',views.patient_master.as_view()), 
    path('user_master_data/',views.user_master.as_view()), 
    path('doctor_master_data/',views.doctor_master.as_view()), 
    path('doctor_patient_master/',views.doctor_patient_master.as_view()), 
    path('edit_profile/',views.edit_profile,name="edit_profile"), 
    path('edit_profile_admin/',views.edit_profile_admin,name="edit_profile_admin"), 
    path('view_ur_patient/',views.view_ur_patient,name="view_ur_patient"), 
    path('edit_profile_doctor/',views.edit_profile_doctor,name="edit_profile_doctor"), 


    path('patient_list_admin/delete_patient/<pk>/',views.delete_patient,name="delete_patient"), 
    path('view_bed_admin/delete_bed/<pk>/',views.delete_bed,name="delete_bed"), 
    path('user_list/delete_user/<pk>/',views.delete_user,name="delete_user"), 
    path('view_doctor/delete_doctor/<pk>/',views.delete_doctor,name="delete_doctor"), 

    path('json_bed/',views.json_bed,name="json_bed"),
    path('json_bed_edit/<pk>/',views.json_bed_edit,name="json_bed_edit")


]

main/models.py
from email.mime import image
from email.policy import default
from operator import mod
from unicodedata import category
from django.db import models
from multiselectfield import MultiSelectField
from django.contrib.auth.models import User

# Create your models here.

class Patient(models.Model):
    name = models.CharField(max_length=50)
    phone_num = models.CharField(max_length=15)
    patient_relative_name = models.CharField(max_length=50, null=True)
    patient_relative_contact = models.CharField(max_length=15, null=True)
    gender_choices = (('M', 'Male'), ('F', 'Female'),)
    gender = models.CharField(max_length=6, choices=gender_choices)
    address = models.CharField(max_length=100, null=True)
    SYMPTOMS = (
        ('Fever', 'Fever'),
        ('Dry cough', 'Dry cough'),
        ('Tiredness', 'Tiredness'),
    )

    comman_symptoms = MultiSelectField(choices=SYMPTOMS,null=True,blank=True,max_length=200)
    SYMPTOMS2 = (
        
        ('Aches and pains', 'Aches and pains'),
        ('Sore throat', 'Sore throat'),
        ('Diarrhoea', 'Diarrhoea'),
        ('Loss of taste or smell', 'Loss of taste or smell'),
    )
    less_symptoms = MultiSelectField(choices=SYMPTOMS2, null=True,blank=True,max_length=200)
    SYMPTOMS3 = (
        ('Difficulty in breathing or shortness of breath', 'Difficulty in breathing or shortness of breath'),
        ('Chest pain or pressure', 'Chest pain or pressure'),
        ('Loss of speech or movement', 'Loss of speech or movement'),
    )
    serious_symptoms =  MultiSelectField(choices=SYMPTOMS3, null=True,blank=True,max_length=200)
    prior_ailments = models.TextField()
    bed_num = models.ForeignKey("Bed", on_delete=models.CASCADE,null=True)
    dob = models.DateField(null=True)
    doctor = models.ForeignKey("Doctor", on_delete=models.CASCADE, null=True)
    status = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
        
class Bed(models.Model):
    yes = 'Yes'
    no = 'No'
    TYPE_CHOICES = (
        (yes, 'Yes'),
        (no, 'No')
    )
    simple = 'Simple'
    ventilator = 'Ventilator'
    BED_TYPE = (
        (simple ,'Simple'),
        (ventilator , 'Ventilator')
    )
    bed_number = models.CharField(max_length=50)
    occupied = models.CharField(max_length=10, choices=TYPE_CHOICES, default=no)
    categories = models.CharField(max_length=10, choices = BED_TYPE, default=simple)
    def __str__(self):
        return self.bed_number


class Doctor(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=100)
    phone_num = models.CharField(max_length=15)
    gender_choices = (('M', 'Male'), ('F', 'Female'),)
    gender = models.CharField(max_length=6, choices=gender_choices)
    dob = models.DateField(null=True)
    email = models.EmailField()
    address = models.TextField()
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    specialization = models.CharField(max_length=150)

    def __str__(self):
        return self.name

class Add_user(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=50)
    phone_num = models.CharField(max_length=15)
    gender_choices = (('M', 'Male'), ('F', 'Female'),)
    gender = models.CharField(max_length=6, choices=gender_choices)
    dob = models.DateField(null=True)
    email = models.EmailField()
    address = models.TextField()
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    password = models.CharField(max_length=9)
    def __str__(self):
        return self.name

class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    location =  models.ImageField(upload_to='images', default='images/visitor.png')

main/views.py
import datetime
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from .models import *
from .filters import PatientFilter,BedFilter,UserFilter,DoctorFilter
from django.contrib.auth.models import User, auth
from django.contrib import messages
from django.contrib.auth.decorators import login_required
import string
from django.core.mail import EmailMessage
from random import *
from django.template.loader import render_to_string
from django.core.files.base import ContentFile
import base64
import time
import json
from django.db.models import Q
from django.core.serializers.json import DjangoJSONEncoder
from django_serverside_datatable.views import ServerSideDatatableView
import validators
# PatientFilter = OrderFilter

# Create your view

def base(request):
    # user = request.user
    # user_id = user.id
    # print('------user----',user)
    # profile_admin = Profile.objects.get(user=user_id)
    # print('----admin---',profile_admin)
    # context = {
    #     'profile_admin' : profile_admin ,
    # }
    # user = request.user
    # doctor_user = Doctor.objects.filter(user_id=user)
    # print("-----doctor-----",doctor_user)
    # show = False
    # if doctor_user.exists():
    #     show = True   
    request(request,'main/base.html')



def login(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            error = {}

            username = request.POST['username']
            password = request.POST['password']
 
            if not validators.length(username, min=2, max=100):
                error['username'] = "Please enter username"
                print('-----------',error)
            if not validators.length(password, min=1):
                error['password'] = "Please enter password"
            if bool(error):
                return JsonResponse({'success': 'false', 'error': error}, status=422)

            user = auth.authenticate(username=username, password=password)

            if 'is_remember_check' in request.POST:
                request.session['username'] = request.POST.get('username')
                request.session['password'] = request.POST.get('password')

            doctor_user = Doctor.objects.filter(user_id=user)
            print("-----doctor-----",doctor_user)
            show = False
            if doctor_user.exists():
                show = True  

            if user is not None and show == False:
                auth.login(request, user)
                request.session['id'] = user.id
               
                response = JsonResponse(
                    {'success': True, 'message': 'Login successful!', 'url': 'dashboard'}, status=200)
                response.set_cookie(key='sa-username',
                                    value=request.POST.get('username'))
                response.set_cookie(key='sa-password',
                                    value=request.POST.get('password'))
                return response
            elif user is not None and show == True:
                auth.login(request, user)
                request.session['id'] = user.id
               
                response = JsonResponse(
                    {'success': True, 'message': 'Login successful!', 'url': 'dashboard2'}, status=200)
                response.set_cookie(key='sa-username',
                                    value=request.POST.get('username'))
                response.set_cookie(key='sa-password',
                                    value=request.POST.get('password'))
                return response
            else:
                    error['password'] = "Credential invalid"
                    return JsonResponse({'success': False, 'error': error}, status=422)

        if request.COOKIES.get('sa-username') and request.COOKIES.get('sa-password'):
            username = request.COOKIES['sa-username']
            password = request.COOKIES['sa-password']
            context_dict = {'username': username, 'password': password}
            return render(request, 'main/login.html', context_dict)
        else:
            context_dict = {'username': '', 'password': ''}
            return render(request, 'main/login.html', context_dict)
        # else:
        #     return render(request, 'main/login.html')
    else:
        return redirect('dashboard')

@login_required(login_url='login')
def logout(request):
    auth.logout(request)
    return redirect('/')

def forgot_password(request):
    if request.method == 'POST':
        error = {}

        email = request.POST['email']
        if not validators.length(email, min=2, max=100):
                error['email'] = "Please enter email id"
        elif not validators.email(email):
                error['email'] = "Please enter valid email id"

        if bool(error):
                return JsonResponse({'success': 'false', 'error': error}, status=422)
                
        user = User.objects.filter(email=email)
        show = False
        print('email',email)
        if user.exists():
            show = True
        print('user',user)
        if show == True :
                user = User.objects.get(email=email)
                characters = string.ascii_letters + string.digits
                password = "".join(choice(characters)for x in range(randint(8, 8)))
                user.set_password(password)
                user.save()

                username = user.username

                un = 'Username: ' + username + '\n'
                pas = 'Password: ' + password + '\n'

                send = un + pas
                em = EmailMessage('Username and Password is send',send,'patelbhumin9177@gmail.com',to=[email])
                em.send()
        else:
            error['email'] = "Email does not exists"
            return JsonResponse({'success': 'false', 'error': error}, status=422)

    return render(request,'main/forgot_password.html')




# def reset_password(request):
#     if request.method == 'POST':
#         error = {}

#         password1 = request.POST['password1']
#         password2 = request.POST['password2']
#         if not validators.length(password1, min=8, max=100):
#                 error['password1'] = "Please enter maximum 8 characters"
#         if not validators.length(password2, min=8, max=100):
#                 error['password2'] = "Please enter maximum 8 characters"
#         if bool(error):
#                 return JsonResponse({'success': 'false', 'error': error}, status=422)

#         if password1 != password2:
#             error['password2'] = 'Password did not match'
#             if bool(error):
#                 return JsonResponse({'success': 'false', 'error': error}, status=422)

#         user = User.objects.get
#     return render(request,'main/reset_password.html')




def dashboard(request):
    user = request.user
    user_id = user.id
    pic = Profile.objects.filter(user=user_id)
    # print('----pic---',pics)
    show = False
    if pic.exists() :
        show = True
    print('------show------',show)
    patients = Patient.objects.all()
    patient_count = patients.count()
    patients_recovered = Patient.objects.filter(status="Recovered")
    patients_deceased = Patient.objects.filter(status="Deceased")
    patients_recovering = Patient.objects.filter(status="Recovering")
    deceased_count = patients_deceased.count()
    recovered_count = patients_recovered.count()
    recovering_count = patients_recovering.count()
    beds = Bed.objects.all()
    beds_available = Bed.objects.filter(occupied='No').count()
    beds_occcupied = Bed.objects.filter(occupied='Yes').count()

    doctor = Doctor.objects.all().count()
    print("----------",doctor)
    context = {
        'patient_count': patient_count,
        'recovered_count': recovered_count,
        'beds_available': beds_available,
        'deceased_count':deceased_count,
        'recovering_count':recovering_count,
        'beds':beds,
        'doctor': doctor,
        'pic' : pic,
        'show' : show,
        'beds_occcupied' : beds_occcupied,  
    }
    print(patient_count)
    return render(request, 'main/dashboard.html', context)

def dashboard2(request):
    user = request.user
    user_id = user.id
    pic = Profile.objects.filter(user=user_id)
    print('----pic---',pic)
    show = False
    if pic.exists() :
        show = True
    print('------show------',show)
    patients = Patient.objects.all()
    patient_count = patients.count()
    patients_recovered = Patient.objects.filter(status="Recovered")
    patients_deceased = Patient.objects.filter(status="Deceased")
    patients_recovering = Patient.objects.filter(status="Recovering")
    deceased_count = patients_deceased.count()
    recovered_count = patients_recovered.count()
    recovering_count = patients_recovering.count()
    beds = Bed.objects.all()
    beds_available = Bed.objects.filter(occupied='No').count()
    beds_occcupied = Bed.objects.filter(occupied='Yes').count()

    doctor = Doctor.objects.all().count()
    print("----------",doctor)
    context = {
        'patient_count': patient_count,
        'recovered_count': recovered_count,
        'beds_available': beds_available,
        'deceased_count':deceased_count,
        'recovering_count':recovering_count,
        'beds':beds,
        'doctor': doctor,
        'pic' : pic,
        'show' : show,
        'beds_occcupied' : beds_occcupied,  
    }
    print(patient_count)
    return render(request, 'main/dashboard2.html', context)

# def dashboard2(request):
#     patients = Patient.objects.all()
#     patient_count = patients.count()
#     patients_recovered = Patient.objects.filter(status="Recovered")
#     patients_deceased = Patient.objects.filter(status="Deceased")
#     patients_recovering = Patient.objects.filter(status="Recovering")
#     deceased_count = patients_deceased.count()
#     recovered_count = patients_recovered.count()
#     recovering_count = patients_recovering.count()

main/templates/main/info.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
        />

        <!-- jquery -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js" integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>

        <!-- bootstrap  -->
        
        <link
        rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous"
        />
        
        <!-- font-awesome -->
        <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
        integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
        crossorigin="anonymous"
        />
        
        
        <!-- google api font -->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;500;600;700&display=swap" rel="stylesheet">

        {% comment %} <link rel="stylesheet" href="info.css"> {% endcomment %}
        <link rel="stylesheet" href="{% static 'styles/info.css' %}">
        <title>Infomation Page</title>
    </head>

    <body>
        <div class="title-body"></i>
            <a {% if show_doctor == True %} href="{%url 'dashboard2'%}" {%else%} href="{%url 'dashboard'%}" {%endif%} ><i class="fa fa-home"></i> Home</a>
            <h3> <a href="https://www.mygov.in/covid-19"> Covid 19 Information</a></h3>
            <div class="heading">
                <p>
                    Stay Home.<br>
                    Stay Safe.
                </p>
            </div>
            <img src="{% static 'images/people-wearing-mask.png' %}" alt="">
            <img href="{% static 'images/WHO.svg' %}"></img>
        </div>
        
        <div class="background-image"></div>

        <div class="container">
            <div class=" row">
                <div class="col-12 col-md-6 col-xl-6">
                    <div class="item-container">
                        <img src="{% static 'images/WHO.svg' %}" alt="">
                    </div>
                </div>
                <div class="col-12 col-md-6 col-xl-6">
                    <a class="d-flex flex-column align-items-center justify-content-center p-3 block" href="https://www.who.int/emergencies/diseases/novel-coronavirus-2019">
                    <div class="label">WHO</div>
                    <div class="description"> Check out the latest guidelines set by the World Health Organisation.</div>
                    </a>
                </div>
                <div class="col-12 col-md-6 col-xl-6">
                    <a class="d-flex flex-column align-items-center justify-content-center p-3 block" href="https://www.cowin.gov.in/">
                    <div class="label"><img src="{% static 'images/cowin.png' %}" alt=""></div>
                    <div class="description">"India is set to defeat Covid-19. <br>
                        Every Indian is making it possible." <br>
                        - PM Narendra Modi</div>
                    </a>
                </div>
                <div class="col-12 col-md-6 col-xl-6">
                    <div class="item-container">
                        <img src="{% static 'images/DotheFive.jpg' %}" alt="">
                    </div>
                </div>
                <div class="col-12 col-md-6 col-xl-6">
                    <div class="item-container">
                        <img src="{% static 'images/national-emblem-of-india.png' %}" alt="">
                    </div>
                </div>
                <div class="col-12 col-md-6 col-xl-6">
                    <a class="d-flex flex-column align-items-center justify-content-center p-3 block" href="https://www.mohfw.gov.in/">
                    <div class="label">Government of India</div>
                    <div class="description">Guidelines given by the gov. of India.</div>
                    </a>
                </div>
            </div>
        </div>          
    </body>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

</html>

main/templates/main/user_list.html
{% extends 'main/base.html' %}
{% load static %}
 
{% block contentTitle %}
    User List 
{% endblock contentTitle %}

{% block admin_pic %}
<img id="pic" name="pic" class="img-circle" {% if show == True %} {% for i in pic %} src="/images/{{i.location}}" {%endfor%} {%else%}  src="{% static 'images/visitor.png' %}" {%endif%} alt="image" width="50px" height="50px" style="margin-right: 15px;">{{request.user}}
{% endblock admin_pic %}

{% block content %}

<style>
    .btn-primary {
    color: #fff;
    background-color: #3a6b7b !important;
    border-color: #3a6b7b !important;
    }

    #id_name {
        width : 360px;
    }
    #id_email {
    margin-right: 0.5rem;
    border: none;
    outline: none;
    border-bottom: 2px solid black;
    width : 360px
    }
    label{
        display: flex;
    }
    .pagination{
    padding-left: 380px;
    }
    .dataTables_length{
        width:37%;
        margin-bottom: 40px;
        margin-top: 20px;
    }
    .dataTables_filter{
        width:70%;
        margin-left: 140px;
        margin-bottom: 40px;
        margin-top: 20px;
    }
    .custom-select-sm
    {
        margin-left : 10px;
        margin-right : 10px;
    }
    .form-control-sm{
        margin-left: 10px;
    }
    .page-item.active .page-link {
    background-color: #3a6b7b;
    border-color: #3a6b7b;
    }

</style>
    <!-- Topbar Search -->
    <!-- <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search mb-3" method="GET" id="user_list">
        <div class="input-group">
        {{myFilter.form}}
            <div class="input-group-append">
                <button class="btn btn-primary btn-block" type="submit">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form> -->
    
     <div class="table-responsive mt-3">
        <table  id="demo-table" class="table table-hover" style="width:100%;">
            <thead>
                <th style="padding-right:150px"><h3>Name</h3></th>
                <th style="padding-right:150px"><h3>Email</h3></th>
                <th style="padding-right:100px"><h3>Gender</h3></th>
                <th><h3>Action</h3></th>
            </thead>

            <tbody>
                <!-- {% for user in users %}

                <tr class="mx-auto">
                    <td scope="row"><h5>{{ users.name }}</h5></td>
                    <td><h5>{{ users.email }}</h5></td>
                    <td><h5>{{ users.address }}</h5></td>
                    <td><a href="/user_update/{{users.id}}" class="btn btn-purple"><h5>Update</h5></a></td>
                </tr>
    
                {% endfor %} -->
                
            </tbody>
        </table>
    
    </div>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script language="javascript">
    $(document).ready(function () {
      $('#demo-table').DataTable({
        serverSide: true,
        Processing : true,
        
        sAjaxSource: "/user_master_data",  // new url
       
        columns: [
          
          { name: "name", data: 0 ,"bSortable": true},
          { name: "email", data: 1, "bSortable": false},
          { name: "gender", data: 2, "bSortable": false},
          { 
            name: 'action', "bSortable": false,
            //user 'render' to append Edit/Delete buttons for each entry
            // render: data => `<a class="btn btn-primary" href="/user_list/user_update/${data}/" action="edit" >Edit</a>`
            render: (data,type,row,meta) => {
              console.log("data : ",row)
              return `<a class="btn btn-primary" href="/user_list/user_update/${data}/" action="edit" 
              style="width: 80px;">Edit</a>`+
                `<a class="btn"  href="/user_list/delete_user/${data}/" action="edit"
                onclick="return confirm('Are you sure you want to delete this record?');"
                style="margin-left: 24px;width: 80px;background-color:#bc0000;color:white;">Delete</a>`
            }
          }
        ],
      });
  
    })
  
  </script>
{% endblock content %}

main/templates/main/view_bed.html
{% extends 'main/base.html' %}
{% load static %}
 
    

{% block contentTitle %}
    Bed List 
{% endblock contentTitle %}

{% block admin_pic %}
<img id="pic" name="pic" class="img-circle" {% if show == True %} {% for i in pic %} src="/images/{{i.location}}" {%endfor%} {%else%}  src="{% static 'images/visitor.png' %}" {%endif%} alt="image" width="50px" height="50px" style="margin-right: 15px;">{{request.user}}
{% endblock admin_pic %}

{% block content %}

    {% comment %} 1)name, 2)bed number, 3)status: critical, less crtical, recovering, recovered
        4)edit option, will display modal that will contain, bed number will change to NA once recovered 
     {% endcomment %}
<style>
    .btn-primary{
        background-color:#3a6b7b !important;
        border-color: #3a6b7b !important;
    }
    .btn-hover{
        background-color:#3a6b7b !important;
    }
    button, input, optgroup, select, textarea {

        margin-left: 8px  !important;
        margin-right: 10px !important;
        line-height: inherit !important;
    }
    #id_bed_number{
        margin-right: 0.5rem ;
        border: none;
        outline: none;
        border-bottom: 2px solid black;
        width: 335px;
    }
    #id_occupied{
        margin-right: 0.5rem;
        border: none;
        outline: none;
        border-bottom: 2px solid black;
        width: 375px;
    }
    label{
        display: flex;
    }
    .pagination{
    padding-left: 379px;
    }
    .dataTables_length{
        width:35%;
        margin-bottom: 40px;
        margin-top: 20px;
    }
    .dataTables_filter{
        width:70%;
        margin-left: 152px;
        margin-bottom: 40px;
        margin-top: 20px;
    }
    .page-item.active .page-link {
    background-color: #3a6b7b;
    border-color: #3a6b7b;
    }
</style>
    <!-- Topbar Search -->
    <!-- <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search mb-3" method="GET" id="list">
        <div class="input-group">
        {{myFilter.form}}

           
            <div class="input-group-append">
                <button class="btn btn-primary btn-block" type="submit">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form> -->
    
     <div class="table-responsive mt-3">
        <table id="demo-table" class="table table-hover" style="width:100%;">
            <thead>
                <th style="padding-right:200px"><h3>Bed no</h3></th>
                <th style="padding-right:200px"><h3>Occupied</h3></th>
                <th><h3>Action</h3></th>
            </thead>

            <tbody>
                <!-- {% for bed in beds %}

                <tr class="mx-auto">
                    <td><h5>{{ bed.bed_number }}</h5></td>
                    <td><h5>{{ bed.occupied }}</h5></td>
                    <td><a href="/update_bed/{{bed.id}}" class="btn btn-purple"><h5>Update</h5></a></td>
                </tr>
    
                {% endfor %} -->
                
            </tbody>
        </table>
    
    </div>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
{% comment %} <script> 
    $( function() {
    
    $( "#searchPatient" ).autocomplete({
      source: '{% url "autocomplete" %}'
    });
  } );
</script>
{% endcomment %}
<script language="javascript">
    $(document).ready(function () {
      $('#demo-table').DataTable({
        serverSide: true,
        Processing : true,
        
        sAjaxSource: "/bed_master_data",  // new url
        // "order": [[ 0, "desc" ]],
        columns: [
          
          { name: "bed_number", data: 0 ,"bSortable": false},
          { name: "occupied", data: 1, "bSortable": false},
          { 
            name: 'action', "bSortable": false,
            //user 'render' to append Edit/Delete buttons for each entry
            // render: data => `<a class="btn btn-primary" href="/view_bed/update_bed/${data}/" action="edit" style="">Edit</a>`
            render: (data,type,row,meta) => {
              console.log("data : ",row)
              return `<a class="btn btn-primary" href="/view_bed/update_bed/${data}/" action="edit" 
              style="width: 80px;">Edit</a>`
            //   +
            //     `<a class="btn"  href="/delete_bed/${data}/" action="edit"
            //     style="margin-left: 24px;width: 80px;background-color:#bc0000;color:white;">Delete</a>`
            }
          }
        ],
      });
  
    })
  
  </script>
{% endblock content %}